version: '2'
services:
  mongo:
    image: mongo:3.4
  web:
    build: .
    ports:
     - "5000:5000"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/dev1
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules